<#
.SYNOPSIS
  Preflight checks for running the asterisk-pbx project from Windows PowerShell.

.DESCRIPTION
  This checks the tools normally used from Windows:
    - OpenTofu: creates the Proxmox VM
    - SSH: lets you test/connect to the VM
    - WSL: recommended place to run Ansible

  It also checks whether the main project variable files exist.
#>

$ProjectRoot = Split-Path -Parent $PSScriptRoot

function Test-CommandPresent {
    param(
        [Parameter(Mandatory=$true)][string]$Name,
        [string]$VersionArgs = "--version"
    )

    $cmd = Get-Command $Name -ErrorAction SilentlyContinue
    if (-not $cmd) {
        return [pscustomobject]@{
            Tool = $Name
            Found = "NO"
            Details = "Not found in PATH"
        }
    }

    $version = "Found at $($cmd.Source)"
    try {
        $output = & $Name $VersionArgs 2>$null | Select-Object -First 1
        if ($output) { $version = $output.ToString() }
    } catch {}

    return [pscustomobject]@{
        Tool = $Name
        Found = "YES"
        Details = $version
    }
}

Write-Host "== Windows tool checks ==" -ForegroundColor Cyan
$checks = @()
$checks += Test-CommandPresent -Name "tofu" -VersionArgs "-version"
$checks += Test-CommandPresent -Name "ssh" -VersionArgs "-V"
$checks += Test-CommandPresent -Name "wsl" -VersionArgs "--version"
$checks | Format-Table -AutoSize

Write-Host "== Project file checks ==" -ForegroundColor Cyan
$projectChecks = @(
    [pscustomobject]@{
        File = "opentofu\terraform.tfvars"
        Exists = (Test-Path (Join-Path $ProjectRoot "opentofu\terraform.tfvars"))
        Purpose = "Your Proxmox/OpenTofu values"
    },
    [pscustomobject]@{
        File = "ansible\group_vars\asterisk_vault.yml"
        Exists = (Test-Path (Join-Path $ProjectRoot "ansible\group_vars\asterisk_vault.yml"))
        Purpose = "Your SIP passwords/secrets"
    },
    [pscustomobject]@{
        File = "ansible\inventory\hosts.ini"
        Exists = (Test-Path (Join-Path $ProjectRoot "ansible\inventory\hosts.ini"))
        Purpose = "Generated by OpenTofu after apply"
    }
)
$projectChecks | Format-Table -AutoSize

if (Get-Command wsl -ErrorAction SilentlyContinue) {
    Write-Host "== WSL Ansible checks ==" -ForegroundColor Cyan
    Write-Host "Checking inside your default WSL distro..."
    wsl bash -lc 'set +e; echo "Distro: $(. /etc/os-release 2>/dev/null && echo ${PRETTY_NAME:-unknown})"; for c in python3 pipx ansible ansible-playbook ansible-galaxy ssh; do if command -v "$c" >/dev/null 2>&1; then printf "%-18s YES  %s\n" "$c" "$(command -v $c)"; else printf "%-18s NO\n" "$c"; fi; done; if command -v ansible >/dev/null 2>&1; then ansible --version | head -n 1; fi'
}

Write-Host ""
Write-Host "If something is missing:" -ForegroundColor Yellow
Write-Host "  Windows/OpenTofu:  .\scripts\install-prereqs.ps1"
Write-Host "  WSL/Ansible:       wsl bash /mnt/c/projects/asterisk-pbx/scripts/install-prereqs-wsl.sh"
Write-Host ""
